# Generated by Django 6.0.3 on 2026-03-13 17:04

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=products.models.product_banner_upload_path),
        ),
    ]
